"""agrega fecha_creacion a Usuario

Revision ID: 3cf17024e963
Revises: a4c8af032ee3
Create Date: 2025-08-04 15:27:49.263876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf17024e963'
down_revision: Union[str, Sequence[str], None] = 'a4c8af032ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'usuarios',
        sa.Column(
            'fecha_creacion',
            sa.DateTime(),
            nullable=False
        )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_creacion')
    # ### end Alembic commands ###
